feat: add tenant page to dashboard page and remove it from the main page
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #163
Opened 2024-05-22 08:57 UTC by yusualhashash

2024-05-22 10:23 UTC, a0m0rajab requested changes
For the merge conflict feel free to do either one of the next: 
- rebase your branch 
- merge the main branch to your branch and resolve the conflicts in your editor 

then this would be ready to merge.

2024-05-22 10:23 UTC, a0m0rajab commented on apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx
>    };
can we have those as one array and have a function to convert to the index to array element and vice versa. ?

2024-05-22 10:23 UTC, a0m0rajab commented on apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx
> +    data: { getRoles, autoFormArgs: params.data === 'tenant' ? { formSchema: editformSchema } : { formSchema }, tableType, excludeList, onEdit, onDelete },
Instead of having a custom condition for tenant only, can we generalize this and have a custom for object passed to the zod to object function convertor?

2024-05-22 10:23 UTC, a0m0rajab commented on apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx
>      formSchema: $Volo_Abp_Identity_IdentityUserCreateDto,
we could have an object here in the next style: 
```js
{
type: "zod",
schema: .... 
}
```
or 
```js
{
type: "json",
schema: ....
}
```
then ignore the zod object in the create zod object function something like the next line:

```js

const formSchema = formSchema.type === "json" ? createZodObject(schema, formPositions) : formSchema.schema
```

2024-05-22 12:32 UTC, yusualhashash commented on apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx
>    };
done

2024-05-22 12:44 UTC, yusualhashash commented on apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx
> +    data: { getRoles, autoFormArgs: params.data === 'tenant' ? { formSchema: editformSchema } : { formSchema }, tableType, excludeList, onEdit, onDelete },
done

2024-05-22 13:23 UTC, ertugrulcan-ays submitted a review, later dismissed

2024-05-22 13:40 UTC, a0m0rajab commented on apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx
>    };
Can you push the changes to the remote repo?

2024-05-23 05:28 UTC, yusualhashash commented on apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx
>    };
`const activationStates = ["Active", "Active with limited time", "Passive"];
function convertActivationState(value: string | number): string | number {
  if (typeof value === "number") {
    return activationStates[value];
  } else {
    return activationStates.indexOf(value);
  }
}`

2024-05-23 09:39 UTC, yusualhashash commented on apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx
> +    data: { getRoles, autoFormArgs: params.data === 'tenant' ? { formSchema: editformSchema } : { formSchema }, tableType, excludeList, onEdit, onDelete },
const getCustomFormArgs = () => {
    if (dataConfig[params.data].FormType === "zod") {
      return { formSchema: editformSchema };
    }
    return { formSchema };
  };

  const columnsData: columnsType = {
    type: "Auto",
    data: { callback:getRoles, autoFormArgs: getCustomFormArgs(), tableType, excludeList, onEdit, onDelete },

2024-05-23 09:39 UTC, yusualhashash commented on apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx
> +    data: { getRoles, autoFormArgs: params.data === 'tenant' ? { formSchema: editformSchema } : { formSchema }, tableType, excludeList, onEdit, onDelete },
`  const getCustomFormArgs = () => {
    if (dataConfig[params.data].FormType === "zod") {
      return { formSchema: editformSchema };
    }
    return { formSchema };
  };

  const columnsData: columnsType = {
    type: "Auto",
    data: { callback:getRoles, autoFormArgs: getCustomFormArgs(), tableType, excludeList, onEdit, onDelete },`

2024-05-23 09:40 UTC, yusualhashash commented on apps/web/src/app/[lang]/(main)/dashboard/[data]/page.tsx
>      formSchema: $Volo_Abp_Identity_IdentityUserCreateDto,
`  const formSchema = dataConfig[params.data].FormType === "zod"
  ? z.object({
      name: z.string().max(64).min(0),
      editionId: z.string().uuid().nullable().optional(),
      adminEmailAddress: z.string().email().max(256).min(0),
      adminPassword: z.string().max(128).min(0),
      activationState: z.enum(['Active', 'Active with limited time', 'Passive']),
    })
  : createZodObject(schema, formPositions);`

2024-05-23 09:45 UTC, closed without merging