feat: add organization page into identity page
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #284
Opened 2024-06-25 10:07 UTC by yusualhashash

2024-06-25 10:43 UTC, a0m0rajab requested changes

2024-06-25 10:43 UTC, a0m0rajab commented on apps/web/src/app/[lang]/(main)/dashboard/[domain]/organization/action.ts
Can we use one fetch function in this file, with generic link? and have the other functions as wrappers if you want, or even use it immediately in the project?

2024-06-25 10:43 UTC, a0m0rajab commented on apps/web/src/app/api/organization/[data]/route.ts
> +}
Can we use this as imports from the `api/admin/[data]/route.ts` file?

2024-06-25 10:43 UTC, a0m0rajab commented on apps/web/src/app/[lang]/(main)/dashboard/[domain]/organization/page.tsx
> +      )}
Can we use one autoform dialog?

2024-06-26 07:39 UTC, yusualhashash commented on apps/web/src/app/[lang]/(main)/dashboard/[domain]/organization/action.ts
done
![image](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/assets/64100035/68d0b054-d61b-4da7-b325-953f14fc014b)

2024-06-26 13:46 UTC, a0m0rajab commented on apps/web/src/app/api/organization/[data]/route.ts
> +}
You can export the function or move it to `utils.ts`.

2024-06-27 13:27 UTC, a0m0rajab approved these changes

2024-06-27 13:27 UTC, merged