Refactor/merchant
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #285
Opened 2024-06-26 13:40 UTC by yusualhashash

2024-06-26 13:43 UTC, a0m0rajab approved these changes
LGTM 👍 
Thanks.

2024-06-26 13:44 UTC, a0m0rajab requested changes

2024-06-26 13:44 UTC, a0m0rajab commented on apps/docs/auth-action.ts
Did we use the docs/auth-action.ts file?

2024-06-27 05:30 UTC, yusualhashash commented on apps/docs/auth-action.ts
yes  i only added th merchantservice to scope for the token

2024-06-27 05:56 UTC, closed without merging

2024-06-27 05:56 UTC, a0m0rajab commented on apps/docs/auth-action.ts
This file is in the docs app, we did not use that app for the development.