feat: add product group page
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #474
Opened 2024-08-08 10:42 UTC by ahmeterenodaci

## Description

## How has this been tested?

- [ ] Prod
- [ ] Development

### Testing Screenshots:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] Added all translations, no hard coded text. 
- [ ] Updated the UI (if needed).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-08-08 10:48 UTC, ahmeterenodaci commented
Bu sayfa baştan yazılacak hızlıca gösterebilmek için bu şekilde yapıldı

2024-08-08 14:11 UTC, a0m0rajab requested changes

2024-08-08 14:11 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/product-group/form.tsx
> +          filterBy="result"
The filter by should one of the inputs of the server for example: 
```suggestion
          filterBy="name"
```

2024-08-08 14:11 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/product-group/loading.tsx
> +        </div>
We have a loading state inside the table itself we can use it.

2024-08-08 14:11 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/product-group/page.tsx
> +      <Form productGroupData={productGroupData} />
Nit: Should we name this as table or data?

2024-08-08 14:11 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/product-group/form.tsx
we could change the file name to table or dashboard?

2024-08-09 06:06 UTC, ahmeterenodaci commented on apps/web/src/app/[lang]/app/[type]/product-group/loading.tsx
> +        </div>
It can be used for data loading but not for page loading.

2024-08-09 11:14 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/product-group/loading.tsx
> +        </div>
@ahmeterenodaci we can use it for page loading.

2024-08-09 12:09 UTC, a0m0rajab approved these changes

2024-08-09 12:10 UTC, merged