feat: add template page
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #477
Opened 2024-08-08 13:42 UTC by yusualhashash

2024-08-08 14:31 UTC, a0m0rajab requested changes
Please update the UI within this PR, and add filtersBy flag to the tables, 

![image](https://github.com/user-attachments/assets/72eb38da-a4b1-41d5-9451-13a7ac65cfd1)

and make sure to have the same alignment for buttons: 

![image](https://github.com/user-attachments/assets/bbaf63c9-0187-455c-9afd-2cdb38796e04)

2024-08-09 06:15 UTC, yusualhashash commented
done can you check it now after update  ui

2024-08-09 09:45 UTC, a0m0rajab approved these changes
Approve in favor of updating it later: 
- the submit function should be functional (at lasting printing json data to the console) 
- the button should be aligned with the table.  
![image](https://github.com/user-attachments/assets/c5f13838-1f25-4c2c-bf24-c0afd75dd468)

2024-08-09 09:45 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/template/rebate/page.tsx
> +  };
We should enable this function.

2024-08-09 09:45 UTC, a0m0rajab commented
@yusualhashash can you fix the lint issues?

2024-08-09 12:35 UTC, merged