refctor: crm page
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #610
Opened 2024-09-09 05:51 UTC by yusualhashash

## Description

## How has this been tested?

- [ ] Prod
- [ ] Development

### Testing Screenshots:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] Added all translations, no hard coded text. 
- [ ] Updated the UI (if needed).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-09-09 09:32 UTC, a0m0rajab requested changes

2024-09-09 09:32 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/form.tsx
> +        setData([]);
do not set the data return a toast error.

2024-09-09 09:32 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/form.tsx
> +      setData([]);
do not set the data return a toast error.

2024-09-09 09:32 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/new/page.tsx
> +  organization: Record<string, string>;
let's define the sub objects of the organization.

2024-09-09 09:32 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/subcompany/new/page.tsx
> +    ];
using a similar concept as convertors would be awesome.

2024-09-09 09:32 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/subcompany/new/page.tsx
> +/* eslint-disable @typescript-eslint/no-unsafe-member-access -- TODO: we need to fix this*/
can we remove the eslint disable.

2024-09-09 09:32 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/subcompany/new/page.tsx
> +        };
do not we have a definitive error?

2024-09-09 10:27 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/new/page.tsx
> +  organization: Record<string, string>;
done

2024-09-09 10:27 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/form.tsx
> +      setData([]);
done

2024-09-09 10:28 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/subcompany/new/page.tsx
> +/* eslint-disable @typescript-eslint/no-unsafe-member-access -- TODO: we need to fix this*/
done

2024-09-09 10:28 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/subcompany/new/page.tsx
> +        };
we add this to remove the any error

2024-09-09 13:19 UTC, a0m0rajab requested changes

2024-09-09 13:19 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/form.tsx
> +        toast.error("Failed to fetch Sub Companies.");
It would be great to use the message from the response

2024-09-09 13:19 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/form.tsx
> +      }
```suggestion
      if (!response.ok) {
       toast.error(response.statusText);
      }
      
     const _data =
          (await response.json()) as Volo_Abp_Application_Dtos_PagedResultDto_18;
     if (_data.items) {
          setData(_data.items);
        }
```

An easier to read pattern.

2024-09-09 13:19 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/form.tsx
> +      toast.error("An error occurred while fetching Sub Companies.");
can we use the error type here and return the error from the server?

2024-09-10 05:53 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/form.tsx
> +      }
```suggestion
      if (!response.ok) {
        toast.error(response.statusText);
        return;
      }
```

2024-09-10 05:55 UTC, a0m0rajab approved these changes

2024-09-10 05:57 UTC, ertugrulcan-ays approved these changes

2024-09-10 05:57 UTC, merged