refactor: crm page
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #630
Opened 2024-09-12 13:44 UTC by yusualhashash

## Description

## How has this been tested?

- [ ] Prod
- [ ] Development

### Testing Screenshots:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] Added all translations, no hard coded text. 
- [ ] Updated the UI (if needed).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-09-13 06:05 UTC, a0m0rajab requested changes

2024-09-13 06:20 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/form.tsx
> +  async function getSubCompaniesInformationForMerchantx() {
no it does not implemented yet

2024-09-13 06:20 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/crm/[domain]/[data]/(alternative)/[id]/form.tsx
> +  const individualSchema = {
done

2024-09-16 06:35 UTC, a0m0rajab requested changes

2024-09-16 06:35 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/actions/merchant.ts
> +export async function getMerchantsByIdSubMerchants(
Can we fix the function name?
```suggestion
export async function getSubMerchantsByMerchantId(
```

2024-09-16 06:35 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/actions/merchant.ts
> +) {
can we apply this too?

2024-09-16 06:35 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/actions/merchant.ts
> +    } as ServerResponse<Volo_Abp_Application_Dtos_PagedResultDto_16>;
we can remove the `as serverResponse from here`

2024-09-16 06:35 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/actions/merchant.ts
> +export async function getMerchantsByIdIndivituals(): Promise<
typo in the function name.

2024-09-16 06:35 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/actions/merchant.ts
> +export async function getMerchantsByIdIndivituals(): Promise<
can we write the name in a better way?

2024-09-16 06:35 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/actions/merchant.ts
> +    } as ServerResponse<Volo_Abp_Application_Dtos_PagedResultDto_16>;
same as before.

2024-09-16 06:35 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/actions/merchant.ts
> +export async function deleteSubMerchantsByIdWithComponents(
let's have a simpler names

2024-09-16 06:35 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/actions/merchant.ts
> +export async function deleteIndivitualsMerchantsByIdWithComponents(): Promise<
lets have a meaningful function name

2024-09-16 06:35 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/actions/merchant.ts
> +    message: "Indivitual deleted successfully.",
let's get the correct message here/

2024-09-16 06:35 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/crm/actions/merchant.ts
> +export async function getMerchantsByIdIndivituals(): Promise<
can we use this in the table page as well?

2024-09-16 10:26 UTC, closed without merging