Translation/management
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #742
Opened 2024-10-10 12:19 UTC by yusualhashash

## Description

## How has this been tested?

- [ ] Prod
- [x] Development

### Testing Screenshots:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] Added all translations, no hard coded text. 
- [ ] Updated the UI (if needed).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-10-10 12:23 UTC, a0m0rajab requested changes
LGTM Just a minor change

2024-10-10 12:23 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/page.tsx
> +  const translationForm = createFieldConfigWithResource({
```suggestion
  const translatedForm = createFieldConfigWithResource({
```

2024-10-10 12:23 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/page.tsx
> +    schema: formData.createFormSchema?.schema as SchemaType,
why did we use ``as SchemaType`` ?

2024-10-10 12:30 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/page.tsx
> +    schema: formData.createFormSchema?.schema as SchemaType,
because this is an manupulated schema and it's type defined as Record<string,any>

2024-10-10 12:49 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/page.tsx
> +    schema: formData.createFormSchema?.schema as SchemaType,
Let's fix the schema type in the crateFormSchem and make it as the correct type here.

2024-10-14 11:43 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/management/[domain]/[data]/page.tsx
> +    schema: formData.createFormSchema?.schema as SchemaType,
we will not fix this now. 
We will need to fix all the types of schema and have a huge refactor. It's out of the scope of this PR.

2024-10-14 11:46 UTC, a0m0rajab approved these changes
we will not fix this now.
We will need to fix all the types of schema and have a huge refactor. It's out of the scope of this PR.

2024-10-14 11:52 UTC, closed without merging