feat: add filter to table comment & make deleteRequest optional
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #775
Opened 2024-10-16 13:48 UTC by ahmeterenodaci

## Description

## How has this been tested?

- [ ] Prod
- [ ] Development

### Testing Screenshots:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] Added all translations, no hard coded text. 
- [ ] Updated the UI (if needed).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-10-16 21:35 UTC, a0m0rajab requested changes

2024-10-16 21:35 UTC, a0m0rajab commented on packages/ui/src/TableComponent/index.tsx
> +    filter?: { [key: string]: string | string[] },
Let's use the same type with filter here, having two different type is error prune

2024-10-16 21:35 UTC, a0m0rajab commented on packages/ui/src/TableComponent/index.tsx
> +    filter?: { [key: string]: string | string[] },
let's unify this type as well

2024-10-17 05:34 UTC, ahmeterenodaci commented on apps/web/src/app/[lang]/app/actions/table.ts
> +  filter?: Record<string, string | string[]>,
https://github.com/eren-ayasofyazilim/ayasofyazilim-ui/commit/35a459c4e49b2cc8ad9a75dd11509eca55bed714#diff-1a9afb2044dcfdbd0ca7ab01349da81aceeaec88cd0cea83e11c21cb5d600e40R331 I make an improvment for arrays. Now we use string or string array.

2024-10-17 06:03 UTC, ahmeterenodaci commented on packages/ui/src/TableComponent/index.tsx
> +    filter?: { [key: string]: string | string[] },
done

2024-10-17 06:04 UTC, ahmeterenodaci commented on packages/ui/src/TableComponent/index.tsx
> +    filter?: { [key: string]: string | string[] },
done

2024-10-17 06:11 UTC, ertugrulcan-ays approved these changes
lgtm

2024-10-17 06:12 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/parties/table-data.tsx
> +        type: "select-multiple" as const,
why did we need as const here?

2024-10-17 06:14 UTC, a0m0rajab approved these changes

2024-10-17 06:14 UTC, merged