refactor(traveller): use tableCompanent instead of DataTable
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #781
Opened 2024-10-17 08:19 UTC by yusualhashash

## Description

## How has this been tested?

- [ ] Prod
- [x] Development

### Testing Screenshots:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] Added all translations, no hard coded text. 
- [ ] Updated the UI (if needed).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-10-17 08:28 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/parties/traveller/new/form.tsx
> +            renderer: (props) => (
can you add the props type?

2024-10-17 11:42 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/parties/traveller/new/form.tsx
> +            renderer: (props) => (
i added them but the  error does not be solved from lint because ertugul added the type of props in the ui, so we do not have to rewrite the type again when we used it inside the autoform but when we use it outside autoform we have to add the type :)

2024-10-17 13:27 UTC, ahmeterenodaci requested changes

2024-10-17 13:27 UTC, ahmeterenodaci commented on apps/web/src/app/[lang]/app/[type]/parties/traveller/new/form.tsx
> +      toast.error("An error occurred while fetching cities.");
use languageData["Fetch.Fail"] for default errors (default)

2024-10-17 13:27 UTC, ahmeterenodaci commented on apps/web/src/app/[lang]/app/[type]/parties/traveller/new/form.tsx
> +      toast.error("An error occurred while fetching countries.");
use languageData["Fetch.Fail"] for default errors (default)

2024-10-17 13:27 UTC, ahmeterenodaci commented on apps/web/src/app/[lang]/app/[type]/parties/traveller/new/form.tsx
> +  const getCountry = async () => {
we can add this to LocationService/actions.ts

2024-10-17 13:27 UTC, ahmeterenodaci commented on apps/web/src/app/[lang]/app/[type]/parties/traveller/new/form.tsx
> +      const response = await getCountries({ maxResultCount: 1000 });
we can add this to LocationService/actions.ts

2024-10-17 14:00 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/parties/traveller/new/form.tsx
> +  const getCountry = async () => {
done

2024-10-17 14:00 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/parties/traveller/new/form.tsx
> +      const response = await getCountries({ maxResultCount: 1000 });
done

2024-10-18 05:36 UTC, eren-ayasofyazilim approved these changes

2024-10-18 05:36 UTC, merged