feat(tag): add filter by travelers and merchant
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #801
Opened 2024-10-24 11:36 UTC by a0m0rajab

## Description

## How has this been tested?

- [ ] Prod
- [ ] Development

### Testing Screenshots:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] Added all translations, no hard coded text. 
- [ ] Updated the UI (if needed).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-10-24 12:06 UTC, yusualhashash approved these changes

2024-10-25 06:05 UTC, yusualhashash submitted a review, later dismissed

2024-10-25 08:17 UTC, eren-ayasofyazilim requested changes

2024-10-25 08:17 UTC, eren-ayasofyazilim commented on apps/web/src/app/[lang]/app/[type]/operations/details/page.tsx
> +      setTravellers(data.items || []);
If you create getTravellersApi like getMerchantsApi, you won't need to use as Volo_Abp.....
You can create this in CrmService/actions.ts.

We only use getTableData for tables.

2024-10-25 09:07 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/operations/details/page.tsx
> +      setTravellers(data.items || []);
I am using the travellers in a table

2024-10-25 11:06 UTC, ertugrulcan-ays commented on apps/web/src/app/[lang]/app/[type]/operations/details/page.tsx
> +      setTravellers(data.items || []);
Didn't we solve the pagedResult tpye problem already

2024-10-25 11:42 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/parties/traveller/actions.ts
> +  };
return the rror

2024-10-25 11:42 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/parties/traveller/actions.ts
> +export async function getTravellers (page: number, filter?: FilterColumnResult) {
write the return type of this function

2024-10-25 11:42 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/operations/details/page.tsx
> +      setTravellers(data.items || []);
we did not have the updated saas version here, 
i think we should update it and get rid of this dependency.

2024-10-28 07:26 UTC, ahmeterenodaci commented on apps/web/src/app/[lang]/app/[type]/operations/details/actions.ts
> +  };
https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/blob/main/apps/web/src/app/%5Blang%5D/app/actions/CrmService/actions.ts

We have the exact function

2024-10-28 07:28 UTC, ahmeterenodaci commented on apps/web/src/app/[lang]/app/[type]/parties/traveller/actions.ts
> +  };
we should create this action in our global action location.

actions/TravellerService/action.ts

2024-10-28 07:31 UTC, ahmeterenodaci commented on apps/web/src/app/[lang]/app/actions/CrmService/actions.ts
> +): Promise<ServerResponse<GetApiCrmServiceMerchantsResponse>> {
We don't need to give this. It will already shows the return type. We might give wrong return type by accident if we manually add this. We should let it handled by typescript.

2024-10-30 07:17 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/actions/CrmService/actions.ts
> +): Promise<ServerResponse<GetApiCrmServiceMerchantsResponse>> {
having the type as function return type make our actions consistant for the whole project.

2024-10-30 07:22 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/operations/details/actions.ts
> +  };
the other action does not meet the type we have in the ui

2024-10-30 08:01 UTC, eren-ayasofyazilim approved these changes

2024-10-30 10:20 UTC, eren-ayasofyazilim approved these changes

2024-10-30 11:47 UTC, ertugrulcan-ays submitted a review, later dismissed

2024-10-30 12:19 UTC, eren-ayasofyazilim approved these changes

2024-10-31 05:12 UTC, ertugrulcan-ays approved these changes

2024-10-31 05:13 UTC, merged