feat(parties/individuals): add new individuals to party & translations
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #829
Opened 2024-11-04 11:05 UTC by ahmeterenodaci

## Description

## How has this been tested?

- [ ] Prod
- [ ] Development

### Testing Screenshots:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] Added all translations, no hard coded text. 
- [ ] Updated the UI (if needed).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-11-04 11:06 UTC, yusualhashash submitted a review, later dismissed

2024-11-04 12:05 UTC, a0m0rajab requested changes

2024-11-04 12:05 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/parties/[partyName]/[partyId]/individuals-table/form.tsx
> +      toast.error(languageData["Fetch.Fail"]);
can we return the error type from the backend?

2024-11-07 05:11 UTC, yusualhashash approved these changes

2024-11-08 05:27 UTC, a0m0rajab approved these changes

2024-11-08 06:10 UTC, merged