feat(management/role): add move all users option in action list
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #843
Opened 2024-11-08 08:47 UTC by yusualhashash

## Description

## How has this been tested?

- [ ] Prod
- [x] Development

### Testing Screenshots:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] Added all translations, no hard coded text. 
- [ ] Updated the UI (if needed).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-11-08 08:55 UTC, a0m0rajab requested changes

2024-11-08 08:55 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/management/data.tsx
>          },
we have an autoform component we can use it here.

2024-11-11 10:41 UTC, a0m0rajab requested changes

2024-11-11 10:41 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/management/data.tsx
> +                    window.location.reload();
lets remove the reload here and open a task in the ui library to fix this issue.

2024-11-11 10:49 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/management/data.tsx
> +                    window.location.reload();
task or issue ?

2024-11-11 11:21 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/management/data.tsx
> +                        />
we do not need to do this because roleList all the time would not be empty because we added a unassign role

2024-11-11 11:39 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/management/data.tsx
> +                    window.location.reload();
done

2024-11-11 12:38 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/management/data.tsx
> +                              No roles available right now.
```suggestion
                              An error occurred please try again later
```

2024-11-11 12:48 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/management/data.tsx
> +                        />
done

2024-11-11 12:48 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/management/data.tsx
> +                              No roles available right now.
done

2024-11-11 13:03 UTC, eren-ayasofyazilim approved these changes

2024-11-11 13:17 UTC, a0m0rajab approved these changes

2024-11-11 13:17 UTC, merged