feat(finance/billing): add new and update forms for billing page
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #853
Opened 2024-11-13 12:54 UTC by yusualhashash

## Description

## How has this been tested?

- [ ] Prod
- [x] Development

### Testing Screenshots:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] Added all translations, no hard coded text. 
- [ ] Updated the UI (if needed).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-11-14 05:19 UTC, ertugrulcan-ays requested changes

2024-11-14 05:19 UTC, ertugrulcan-ays commented on apps/web/src/app/[lang]/app/[type]/finance/billing/[billingId]/form.tsx
> +      window.location.reload();
can we use router from next/navigation

2024-11-14 05:30 UTC, ertugrulcan-ays approved these changes

2024-11-14 05:32 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/finance/billing/[billingId]/form.tsx
> +      window.location.reload();
done

2024-11-14 06:49 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/finance/billing/new/page.tsx
> +    (merchant.type === "success" && merchant.data.items) || [];
what if we got an error?

2024-11-14 06:50 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/finance/billing/new/form.tsx
> +      toast.error(response.message || languageData["Billing.New.Error"]);
let's pass the error type as well.

2024-11-14 06:50 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/finance/billing/new/form.tsx
> +      router.push(getBaseLink(`/app/admin/finance/billing`));
are we doing this to close the form?

2024-11-14 06:50 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/finance/billing/[billingId]/page.tsx
> +  const billingList = billing.type === "success" && billing.data;
what if we got an error? how will we understand that?

2024-11-14 06:51 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/finance/billing/[billingId]/form.tsx
> +      router.refresh();
if we are doing this to close the form then no need for that.

2024-11-14 06:52 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/finance/billing/[billingId]/form.tsx
> +      toast.error(response.message);
Let's pass the type and handle an empty string case as well here

2024-11-14 08:50 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/finance/billing/new/page.tsx
> +    (merchant.type === "success" && merchant.data.items) || [];
The array  will come as empty and i remmeber we opened an issue for it previously

2024-11-14 09:43 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/finance/billing/new/page.tsx
> +    (merchant.type === "success" && merchant.data.items) || [];
From a user perspective we should provide the error message.

2024-11-14 10:01 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/finance/billing/new/form.tsx
> +      toast.error(response.message || languageData["Billing.New.Error"]);
done

2024-11-14 10:02 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/finance/billing/new/form.tsx
> +      router.push(getBaseLink(`/app/admin/finance/billing`));
no to return the main page after adding

2024-11-14 10:02 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/finance/billing/[billingId]/page.tsx
> +  const billingList = billing.type === "success" && billing.data;
The array will come as empty and i remmeber we opened an issue for it previously

2024-11-14 10:03 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/finance/billing/[billingId]/form.tsx
> +      router.refresh();
no we use it to refresh the new values

2024-11-14 10:03 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/finance/billing/[billingId]/form.tsx
> +      toast.error(response.message);
done

2024-11-14 10:24 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/finance/billing/new/page.tsx
> +    (merchant.type === "success" && merchant.data.items) || [];
you are right
 but we (me and ahmet) did all the pages as here so we can discuss this in the next week to take a decision

2024-11-14 11:48 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/finance/billing/new/page.tsx
> +    (merchant.type === "success" && merchant.data.items) || [];
done

2024-11-14 12:50 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/finance/billing/[billingId]/page.tsx
> +        {billing.message || languageData["Billing.Fetch.Fail"]}
done

2024-11-14 13:04 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/finance/billing/[billingId]/form.tsx
> +      router.refresh();
done after remove it

2024-11-14 13:04 UTC, yusualhashash commented on apps/web/src/app/[lang]/app/[type]/finance/billing/new/page.tsx
> +    (merchant.type === "success" && merchant.data.items) || [];
done

2024-11-15 12:17 UTC, a0m0rajab approved these changes

2024-11-15 12:17 UTC, a0m0rajab commented on apps/web/src/app/[lang]/app/[type]/finance/billing/new/page.tsx
> +    (merchant.type === "success" && merchant.data.items) || [];
This was handled in the form component, if success was true it would work well, otherwise it will disable the related field and show it as error.

2024-11-15 12:17 UTC, merged