refactor: middleware auth check
ayasofyazilim-clomerce/ayasofyazilim-core-project pull request #99
Opened 2024-05-10 14:19 UTC by eren-odaci

2024-05-10 14:40 UTC, a0m0rajab requested changes
Instead of using

2024-05-10 14:40 UTC, a0m0rajab commented on apps/public_web/src/middleware.ts
> +    if (!isAuth) return false;
What is the advantage of getting the token instead of checking the session? Is this way better than the default suggestion in the docs? 

https://authjs.dev/getting-started/session-management/protecting#nextjs-middleware

https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/blob/8f1b40fff7e14cf0c089b8c3d8987c642a3f4125/apps/web/src/middleware.ts#L87-L92

2024-05-13 06:04 UTC, eren-odaci commented on apps/public_web/src/middleware.ts
> +];
When authorized person try to enter unauthorizePages, middleware will redirect him to profile page. Maybe we can rename it to authPages.
PublicUrl's are ones that do not require authentication.

To let visitor to see a page -> add it to publicURLs
to prevent user to see a page -> add it to unauthorizedPages

2024-05-13 06:08 UTC, eren-odaci commented on apps/public_web/src/middleware.ts
> +    if (!isAuth) return false;
Actually last time I check it was redirecting to http://192.168.1.38:44325 as base url. But I checked it again and made a few changes, now it works. We can switch it back. I will make a commit.

2024-05-13 07:07 UTC, merged